### ISSUE TITLE
Skip Rows

### ISSUE THREAD

**Issue by radbrt** [MeltanoLabs/tap-sftp#12]
We came into an issue where the first row of files were jibberish and needed to be skipped. I wrote a new config for this, allowing users to specify the number of lines to skip in the file. By default, the number is zero.

The draft change is at https://github.com/radbrt/tap-sftp/tree/skiprows

I might have three questions regarding this:
- Is this a common enough issue that we should add it to the repo? This isn't the first time I have had to deal with it, but maybe I have strange employers.
- Is the nomenclature "Skip rows" OK? Different tools seems to vary between specifying the number of rows to skip, and what the first row to be read should be.
- The drafts does not check if the option is set, but automatically skips a number of lines (usually 0, the default). This works, but might there be a reason to wrap it in an if-statement? I don't really see why, but who knows.

Any thoughts @pnadolny13 ?

**Comment by pnadolny13** [comment]
@radbrt interesting, do you know the reason behind the jibberish row? The tap already reads in the CSV as a [dictionary using the first row](https://docs.python.org/3/library/csv.html#csv.DictReader) headers as keys. So does that mean that the first row is jibberish, followed by a header row, then a data row?

It seems like a fine feature to add as long as its optional and defaults to the current behavior.

**Comment by radbrt** [comment]
@pnadolny13 the current case is basically a numeric column ID that references a metadata file as a first row. Column names (the "real" csv headers) follows on line two. The second variation was someone that liked to place the SQL query that generated the csv above the csv content. That last case is especially unfortunate, but in both cases it was basically RFC-4180 compliant files prepended with some non-relevant lines.

I'll fashion a PR for it, after we have merged the sanitize-header PR.
